name: CodeFreeze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.4]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g moment codefreeze@1.0.0 && npm list -g
      - run: |
          cat $(cat GITHUB_ENV) | grep CODE_FREEZE_DAY_BEGIN= | head -n 1 | grep -o '".*"' | sed 's/"//g' > CODE_FREEZE_DAY_BEGIN
          cat $(cat GITHUB_ENV) | grep CODE_FREEZE_HOUR_BEGIN= | head -n 1 | grep -o '".*"' | sed 's/"//g' > CODE_FREEZE_HOUR_BEGIN
          cat $(cat GITHUB_ENV) | grep CODE_FREEZE_DAY_END= | head -n 1 | grep -o '".*"' | sed 's/"//g' > CODE_FREEZE_DAY_END
          cat $(cat GITHUB_ENV) | grep CODE_FREEZE_HOUR_END= | head -n 1 | grep -o '".*"' | sed 's/"//g' > CODE_FREEZE_HOUR_END
          cat $(cat GITHUB_ENV) | grep CODE_FREEZE_BI_WEEKLY= | head -n 1 | grep -o '".*"' | sed 's/"//g' > CODE_FREEZE_BI_WEEKLY
          cat $(cat GITHUB_ENV) | grep CODE_FREEZE_OVERRIDE= | head -n 1 | grep -o '".*"' | sed 's/"//g' > CODE_FREEZE_OVERRIDE
          node /opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/codefreeze/index
